name: Manual Pages Rebuild

on:
  workflow_dispatch:
    inputs:
      clean_build:
        description: 'Выполнить полную очистку'
        required: true
        default: 'true'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Clean gh-pages branch
        if: ${{ github.event.inputs.clean_build == 'true' }}
        run: |
          git checkout gh-pages
          git rm -rf .
          git clean -fdx
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Build
        run: |
          npm ci
          npm run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
